### ISSUE TITLE
Idea: declarative as config, instead of code

### ISSUE THREAD

**Issue by potating-potato** [pyapp-kit/app-model#55] opened 2022-08-10 01:05 UTC
I really like where we are going in terms of making GUI declarative, along the way there are some quite notable things you did leading us here. (magic GUI, manifest, etc.).

I would want to throw this idea out to move this one step forward. Why not declare the GUI as config files instead of python code? Coming from the java world, I liked the spring framework of managing objects (which we are also doing the injection part lightweight via in-n-out, thanks!) And I would say there are additional benefits if we switch to file declaration from code declaration. (and I am in no way trying to say we should follow spring to use XML as the format)

* Developers can then run schema checks without additional tooling
* versioning can be more explicit by marking them out, potentially having better multi-version support
* simplify some verbosity with coding

Take the example app as an example. [actions.py](https://github.com/napari/app-model/blob/main/demo/multi_file/actions.py) can be rewritten to actions.yml. We can probably drop the total amount of text by 50%+

and by having the declaration via a config file, the downstream application can declare a set of things supported instead of being injected directly. For example, the app can also declare in the configuration that "Ctrl is reserved for system use and no one can override," etc.

**Comment by tlambert03** [comment] 2022-08-10 01:18
yeah, we (@jni and @ctrueden) discussed this a bit.  There's nothing preventing this, and it would certainly be simple enough to build in support for this sort of thing.  I'm supportive of adding code to make it generally possible, but not sure that we should immediately go in that direction for napari.  For one thing, I suspect a real-world implementation would quickly become a _massive_ file... so we'd also need logic to merge multiple files and deal with conflicts (not too hard).

The second issue there is that declaring callbacks as string `python_names` is much more restrictive than being able to directly pass a callback (like a partial, etc...).  So it might cause some _slightly_ less attractive python-side code in order to accommodate it.

In terms of simplifying verbosity... yes and no: since python could make `Action` subclasses that encapsulated mostly repeated logic, or variables that capture constants used across multiple actions (like [here](https://github.com/napari/napari/blob/a23740339b1e78822f6c6996f05973d3f5bef2df/napari/_app_model/actions/_layer_actions.py#L27-L38)), but yaml would have to reproduce them every time.   While we  don't do that in the example app, I do expect it to be much more common in a real-world app.

The IDE experience would also require more tooling (e.g. json schema exporting, and registration with some IDE plugin to provide auto-completion and stuff) in order to match the experience of python files.  So until all that is done, I think it would actually be a poorer experience.  (All that would be good stuff to have, but probably a pre-requisite for yaml-based configs to be something i'd personally really want to use).

Anyway, i'm generally supportive.  It's definitely something we shouldn't take any steps to make _harder_.  But i'd want to see some real-world implementations before i get too enthused by the concept :smile:

**Comment by tlambert03** [comment] 2022-08-10 01:21
If you'd like to see more examples of where the general pattern got it's inspiration, search the vscode code base for `registerAction2`, where you'll see a gazillion examples of how _they_ define their actions at runtime.  (They also avoid a fully declarative definition, and put it in their javascript files... not sure what decisions went into that, but it's worth noting)

**Comment by tlambert03** [comment] 2022-08-10 01:35
Perhaps a start on this idea could be an overload to application.register_actions that accepts a filepath.

**Comment by potating-potato** [comment] 2022-08-10 01:37
Agreed we shouldn't pursue this immediately. There seems to be enough things blocking 0.5.0 :) 

I am open to starting small and seeing how it works as well, I can give it a try this weekend

**Comment by tlambert03** [comment] 2023-05-30 20:32
this is a low enough priority, and given the number of other things on all of our plates, i'm going to close this as "wont implement" any time soon.  If anyone stumbles on this later and wants to pick it up, feel free to comment

**Closed by tlambert03** 2023-05-30 20:32 UTC
Labels: enhancement
